### ISSUE TITLE
cache directory : how to?

### ISSUE THREAD

**Issue by GPL71** [skrollme/homebridge-people-x#1]
Hello and thank you for your work.
I'm trying setting your plugin but I have a problem with follow instruction:

cacheDirectory 	optional, default: "./.node-persist/storage"
I'm having an error and hombridge fall down
Can you help me step by step how to create the path?
After is possible I need install node-persist via terminal

Thank you in advance

**Comment by skrollme** [comment]
This part of the README was copied from the original plugin I forked mine from. I did not create this directory either, so I don't know what is wrong with your setup.
