### ISSUE TITLE
Change of status is not recognized

### ISSUE THREAD

**Issue by MikeDeltaHH** [skrollme/homebridge-people-x#10]
Good morning!
Recently I've been getting more and more often the problem that the plugin doesn't implement the change of the statute of the Nuki! I have two automations in my settings, one that should be done when I leave the house - door should be locked, all lights off and camera on and one that should be done when I come back home - when I leave the house the door is locked and the plugin shows the corresponding status - but when I come back home the door is unlocked, this status is shown in the Nuki, all automations work but in Homebridge the door is still shown as "closed" - I have to restart Homebridge for the plugin to recognize the correct status! In the Homebridge log I can't find anything that indicates an error... can you help me here?

Here is my config for it:

{
            "bridgeApiPort": 8080,
            "bridgeApiToken": "xxx",
            "bridgeIpAddress": "xxx",
            "bridgeRebootSwitch": true,
            "devices": [
                {
                    "isContinuousModeEnabled": false,
                    "isRingToOpenEnabled": false,
                    "nukiId": xxx,
                    "unlatchFromLockedToUnlocked": false,
                    "unlatchFromUnlockedToUnlocked": false,
                    "unlatchLock": false
                }
            ],
            "hostCallbackApiPort": 40506,
            "hostNameOrIpAddress": "xxx",
            "platform": "NukiPlatform",
            "plugin_map": {
                "plugin_name": "homebridge-nuki"
            }

Regards!
Mike

**Comment by skrollme** [comment]
I don't know anything about the nuki-plugin, so I'm sorry but I can not help you with this.

**Comment by MikeDeltaHH** [comment]
Sorrry Mate, make a mistake - wrong channel!
