### ISSUE TITLE
Doesn't work on Synology DSM 7

### ISSUE THREAD

**Issue by johnnygoodface** [skrollme/homebridge-people-x#15]
Just ported Homebridge from rPi to Synology NAS and all is working on the Homebridge Native App (no docker, real new HB native app), all but PeopleX. The config looks fine in config.json (like on the rPi), I'm able to ping FROM my NAS to my iPhone (192.168.1.50) - using SSH, I've disabled the firewall, to no avail. Presence detection is not showing in HB logs when I go from LTE to WiFi on my phone. Any idea?

            "platform": "PeopleX",
            "threshold": 1,
            "anyoneSensor": false,
            "nooneSensor": false,
            "webhookPort": 24999,
            "cacheDirectory": "./.node-persist/storage",
            "pingInterval": 1000,
            "ignoreReEnterExitSeconds": 0,
            "people": [
                {
                    "name": "Jean is Home",
                    "target": "192.168.1.50",
                    "threshold": 15,
                    "pingInterval": 1000,
                    "ignoreReEnterExitSeconds": 0
                },
                {
                    "name": "Mario is Home",
                    "target": "192.168.1.204",
                    "threshold": 15,
                    "pingInterval": 1000,
                    "ignoreReEnterExitSeconds": 0
                }
            ]
        }

Thx

**Comment by skrollme** [comment]
To be honest.. I have no idea, @johnnygoodface :D I'm sorry. And because I have no Synology NAS it is hard to debug for me. Are you able to see the Homebridge logs on the NAS? You should see something like this on Homebridge startup:

```
homebridge_app | [2/4/2022, 3:49:41 PM] [PeopleX] Initializing PeopleX platform...
homebridge_app | [2/4/2022, 3:49:41 PM] [PeopleX] WebHook: Started server on port '51828'.
homebridge_app | [2/4/2022, 2:16:21 PM] [PeopleX] Changed occupancy state for XY
```

**Comment by johnnygoodface** [comment]
Yes I am: before i could see the connection webhook log (from memory: webhook, detected the presence of 192.168.1.76) in the HB log, but now nothing is showing up in the log. I think the issue is that peoplex seems to be using the ping command to detect the presence of a device, but I don't think DSM7 allows using the ping command without root privilege. So essentially, how do we allow a HB plugin to use the Ping command?

**Comment by skrollme** [comment]
Hello @johnnygoodface, I'm sorry but I have no idea how to do this. As mentioned before I do not own a Sinology DSM and have no knowledge on how to do these things. Maybe this is not possible at all.
I would suggest you to research for other presence-detection plugins which state a compatibility with Synology's NAS
