### ISSUE TITLE
Difference between threshold and IgnoreReEnterExitSeconds?

### ISSUE THREAD

**Issue by mensa84** [skrollme/homebridge-people-x#2]
Hello,

can anyone please explain the difference between threshould and IgnoreReEnterExitSeconds?
I don't understand in which case the IgnoreReEnterExitSeconds setting should be used.

**Comment by skrollme** [comment]
I have no idea what the initial plans were, _threshold_ seems to be used in general and _IgnoreReEnterExitSeconds_ only in the web hook. If you want to know it more exactly, read the code
