### ISSUE TITLE
Motion sensors instead of occupancy sensors?

### ISSUE THREAD

**Issue by mensa84** [skrollme/homebridge-people-x#3]
Hello,

because of which reason is that plugin using motion sensors instead of occupancy sensors (as the original plugin)?

**Comment by skrollme** [comment]
I think the reason for the switch to motion-sensors was, that the original EVE HomeKit Sensors also act as motion sensors in HomeKit.

**Comment by mensa84** [comment]
Which original sensors are you talking about? I think that no "original" occupancy sensors do exist.

**Comment by skrollme** [comment]
I was talking about the _EVE motion_ device.

**Comment by mensa84** [comment]
Ok and you use that only because of the history or for which reason?

**Comment by skrollme** [comment]
The idea was to come as close to the EVE Motion as possible, yes.

**Comment by mensa84** [comment]
I am not sure if a motion sensor is really the correct sensor to monitor occupancy.

**Comment by skrollme** [comment]
Feel free to fork this repository and make your own plugin which works exactly as you like
