### ISSUE TITLE
ignoreReEnterExitSeconds parameter in minutes/seconds?

### ISSUE THREAD

**Issue by jqnatividad** [skrollme/homebridge-people-x#5]
The documentation gives conflicting guidance. It says:

> optional, in **minutes,** default: 0, if set to 0 than every enter/exit will trigger state change otherwise the state will only change if no re-enter/exit occurs in specified number of **seconds**

**Comment by skrollme** [comment]
Hello @jqnatividad , you are right this is misleading. This part of the documentation was copied from the origin of this fork, but I will fix it in this repo. Thank you for the hint
