### ISSUE TITLE
arp functionality

### ISSUE THREAD

**Issue by MikeDeltaHH** [skrollme/homebridge-people-x#8]
Hi!

Is it possible to an arp functionality like this plugin?

https://github.com/stickpin/homebridge-people-arp

My wife has a Samsung smartphone and this is often not reachable via ping in my wlan so my homekit rules doen´t works properly! With arp the accuracy is much more better, but the people-arp plugin haven´t an anyone and noone sensor i needed...

Regards!
Mike

**Comment by skrollme** [comment]
Hello @MikeDeltaHH 
at the moment this is not planned but I will keep this Issue open as a reminder.  Maybe sometime in the future. 
But wouldn't this be good occasion for you to start programming? ;) Fork this plugin, implement the desired functionality and make a PR

**Comment by MikeDeltaHH** [comment]
Hi @skrollme! 
Thanks for your answer... will wait and see... programming is not my thing! :)
Regards!
Mike

**Comment by Salvora** [comment]
+1 for ARP if you can add it.

**Comment by skrollme** [comment]
If anyone is till interested in ARP support, did you checked out this plugin: https://www.npmjs.com/package/homebridge-people-arp
